In [6]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,12])
print(arr1+arr2)

[ 6  8 10 16]


In [1]:
1+2


3

In [7]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [4]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
import numpy as np
import matplotlib.plot as plt

In [4]:
import numpy as np
import matplotlib.plot as plt
arr = np.linspace(0,2,9)
y = [x**3 for x in arr]
plt.plot(arr,y)

ModuleNotFoundError: No module named 'matplotlib.plot'

In [13]:
import pymysql
try:
    conn = pymysql.connect(host="localhost",user="root",passwd="xiehongwang",db="commissions",charset="utf8")
    cursor = conn.cursor()
    sql = "select * from User;"
    cursor.execute(sql)
    res = cursor.fetchall()
    print(res)
    conn.close()
except pymysql.Error as e:
    print("Error",e)
    conn.rollback()
    


Error (2003, "Can't connect to MySQL server on '172.20.124.12' (timed out)")


AttributeError: 'str' object has no attribute 'rollback'